# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61340f0f2eaf98bc79dd26026ec6433f1139ff35c54dece3a115ab1cfa07f6eadb8968c9235c2d2535f8f402b45b40e0aff5c2d27f8f2165bae35f3b880b6bdd

test:
  secret_key_base: bbe38ba8dbeb6abea6c52b96c2c57337dc9c6076dea79668b3bbb8f7961f3c1adeb2dc566e662c52dbe5b13e1f65f22f34d2a3c315bf53e3a25e78d204a44781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
